language: python
python:
  - "3.5"
install:
  - pip install -r requirements/dev.txt
  - cp qproject/config_example.py qproject/config.py
before_script:
  - python manage.py migrate
script:
  - python manage.py test

notifications:
  email: false