version: "3"
services:

  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]

  gateway:
    image: kirovverst/gateway
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - variables.env
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - rabbit

  flower:
    image: totem/celery-flower-docker
    environment:
      - AMQP_HOST=rabbit
      - AMQP_ADMIN_HOST=rabbit
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - "5555:5555"
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - rabbit

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  worker:
    image: kirovverst/worker
    env_file:
      - variables.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    command: celery worker -A qproject -l info --autoscale=4,1
    networks:
      - webnet
    depends_on:
      - rabbit
networks:
  webnet:
