version: "3"
services:

  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    image: kirovverst/gateway
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/qproject
    ports:
      - "8000:8000"

  flower:
    image: kirovverst/gateway
    volumes:
      - .:/qproject
    deploy:
      placement:
        constraints: [node.role == manager]
    command: celery flower -A qproject
    ports:
      - "5555:5555"

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  worker:
    image: kirovverst/gateway
    volumes:
      - .:/qproject
    command: celery worker -A qproject -l info
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure